services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./user_data:/app/user_data
      - ./.env:/app/.env
    depends_on:
      - qdrant
      - postgres
    environment:
      - QDRANT_URL=http://qdrant:6333
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ragchatbot
      - STORE_PLAIN_PASSWORDS=true
    networks:
      - app-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-network
    restart: unless-stopped
    
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ragchatbot
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local
  postgres_data:
    driver: local 